Bot:
  clientId:
  tokenId:
host: https://api.nftrainbow.xyz/
app:
  appId:
  appSecret:
chainType: conflux_test
easyMint:
  fileUrl:
  name:
  description:
mintRespPrefix: https://testnet.confluxscan.io/nft/cfxtest:acgraybn1g1upesed09g96vxev79sdhmxjmz7bxzyy/
customMint:
  fileUrl:
  name:
  description:
  contractType:
  contractAddress:
